export * from './IBaseEntity';
export * from './IDeviceQuery';
export * from './IResponse';
export * from './IServerToVictimEvents';
export * from './IServerToWebEvents';
export * from './IVictim';
export * from './IVictimQuery';
export * from './IVictimToServerEvents';
export * from './IWebToServerEvents';
